name: CI/CD FOR PROD

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Generate secret keys
        env: 
          RSA_PRIVATE_KEY: ${{ secrets.RSA_PRIVATE_KEY }}
        run: |
          cd src/main/resources
          touch teste.pem
          echo "$RSA_PRIVATE_KEY" > teste.pem
          openssl rsa -inform PEM -in teste.pem -outform PEM -out rsaPrivateKey.pem
          file -i rsaPrivateKey.pem
          openssl rsa -pubout -in rsaPrivateKey.pem -out publicKey.pem
          openssl pkcs8 -topk8 -nocrypt -inform pem -in rsaPrivateKey.pem -outform pem -out privateKey.pem
          cd ../../..
      - name: Build container
        run: |
          mvn clean package\
            -Dquarkus.container-image.build=true\
            -Dquarkus.container-image.group=registry.heroku.com/api-auth-petinder\
            -Dquarkus.container-image.name=web\
            -Dquarkus.container-image.tag=latest
      - name: Login to Heroku and Release container
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku container:login
          docker push registry.heroku.com/api-auth-petinder/web
          heroku container:release web --app api-auth-petinder
