name: CI/CD FOR PROD

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Generate secret keys
        env: 
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
        run: |
          cd src/main/resources
          touch privateKey.pem
          touch publicKey.pem
          echo $PRIVATE_KEY > privateKey.pem
          echo $PUBLIC_KEY > publicKey.pem
          echo privateKey.pem
          cd ../../..
      - name: Build container
        run: |
          mvn clean package\
            -Dquarkus.container-image.build=true\
            -Dquarkus.container-image.group=registry.heroku.com/api-auth-petinder\
            -Dquarkus.container-image.name=web\
            -Dquarkus.container-image.tag=latest
      - name: Login to Heroku and Release container
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku container:login
          docker push registry.heroku.com/api-auth-petinder/web
          heroku container:release web --app api-auth-petinder
